#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_WS GPIO_NUM_16
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_6

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_4
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_12
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_11
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define WAKEUP_BUTTON_GPIO      GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_39
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_40

// --- CẤU HÌNH MÀN HÌNH OLED 0.96 INCH I2C CHO MẠCH TÍM ---
#define DISPLAY_SDA             GPIO_NUM_11 // Chân IO11/SDA trên mạch tím
#define DISPLAY_SCL             GPIO_NUM_12 // Chân IO12/SCL trên mạch tím
#define DISPLAY_WIDTH           128         // Chiều rộng chuẩn OLED
#define DISPLAY_HEIGHT          64          // Chiều cao chuẩn OLED

#define SECONDS_TO_SLEEP_MODE   (60U * 15U)  // 15 minutes
#define SECONDS_TO_SHUTDOWN     (60U * 30U) // 30 minutes

#endif // _BOARD_CONFIG_H_
